# Generated by Django 2.0.2 on 2019-01-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='overview',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
