# Generated by Django 2.0.2 on 2019-01-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='overview',
            field=models.CharField(default='', max_length=200),
        ),
    ]
